"""One-time seed script: ports the hardcoded restaurant data that used to live
in the frontend's js/data.js into the SQLite database via the SQLAlchemy models.
Run with: python seed.py
"""

from sqlalchemy import text

from app import create_app
from app.extensions import db
from app.models import Cuisine, Feature, Hour, Restaurant

DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

RESTAURANTS_DATA = [
    {
        "id": 1,
        "name": "Al-Bawadi Grill",
        "cuisine": ["Lebanese", "Mediterranean"],
        "area": "Bridgeview",
        "address": "7216 W 87th St, Bridgeview, IL 60455",
        "phone": "(708) 599-1999",
        "rating": 4.6,
        "reviewCount": 842,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2008,
        "description": "One of Chicagoland's most beloved Lebanese restaurants, Al-Bawadi has been serving authentic Zabiha Halal cuisine since 2002. Famous for house-made shawarma, charcoal-grilled meats, fresh baked pita, and an expansive mezze spread. A staple of the southwest suburban halal scene.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Al-Bawadi+Grill+Bridgeview+IL",
        "lat": 41.7376, "lng": -87.8145,
        "emoji": "🥙",
        "bannerGradient": "linear-gradient(135deg, #1B4332 0%, #2D6A4F 100%)",
    },
    {
        "id": 2,
        "name": "Pita Inn",
        "cuisine": ["Mediterranean", "Middle Eastern"],
        "area": "Skokie",
        "address": "3910 Dempster St, Skokie, IL 60076",
        "phone": "(847) 677-0211",
        "rating": 4.5,
        "reviewCount": 1204,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2005,
        "description": "A Chicagoland institution for over 30 years, Pita Inn is celebrated for its fresh Mediterranean food, affordable prices, and consistent quality. Their falafel, chicken shawarma, and hummus are legendary. Multiple locations across the northern suburbs.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "10 AM – 10 PM", "Tue": "10 AM – 10 PM", "Wed": "10 AM – 10 PM",
            "Thu": "10 AM – 10 PM", "Fri": "10 AM – 11 PM", "Sat": "10 AM – 11 PM", "Sun": "10 AM – 10 PM",
        },
        "mapsQuery": "Pita+Inn+Skokie+IL",
        "lat": 42.0400, "lng": -87.7395,
        "emoji": "🫓",
        "bannerGradient": "linear-gradient(135deg, #1A3A5C 0%, #2E6DA4 100%)",
    },
    {
        "id": 3,
        "name": "Sabri Nihari",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Devon Ave)",
        "address": "2502 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 465-3272",
        "rating": 4.7,
        "reviewCount": 986,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2003,
        "description": "An iconic Devon Avenue destination that has defined Pakistani cuisine in Chicago for decades. Sabri Nihari is renowned for its slow-cooked nihari, tender karahi, and aromatic biryani. The restaurant earned its legendary status through consistent, home-style cooking and generous portions.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 11 PM", "Tue": "11 AM – 11 PM", "Wed": "11 AM – 11 PM",
            "Thu": "11 AM – 11 PM", "Fri": "11 AM – 12 AM", "Sat": "11 AM – 12 AM", "Sun": "11 AM – 11 PM",
        },
        "mapsQuery": "Sabri+Nihari+Chicago+IL",
        "lat": 41.9979, "lng": -87.6875,
        "emoji": "🍛",
        "bannerGradient": "linear-gradient(135deg, #7B2D00 0%, #C45500 100%)",
    },
    {
        "id": 4,
        "name": "Bundoo Khan Restaurant",
        "cuisine": ["Pakistani", "BBQ"],
        "area": "Chicago (Devon Ave)",
        "address": "2601 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 764-7755",
        "rating": 4.4,
        "reviewCount": 612,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2006,
        "description": "Named after the famous Lahori restaurant chain, Bundoo Khan brings the smoky flavors of Pakistani BBQ to Devon Avenue. Known for their seekh kebabs, boti, and charcoal-grilled chicken tikka. A crowd favorite for family gatherings and late-night dining.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "12 PM – 11 PM", "Tue": "12 PM – 11 PM", "Wed": "12 PM – 11 PM",
            "Thu": "12 PM – 11 PM", "Fri": "12 PM – 12 AM", "Sat": "12 PM – 12 AM", "Sun": "12 PM – 11 PM",
        },
        "mapsQuery": "Bundoo+Khan+Restaurant+Chicago+IL",
        "lat": 41.9979, "lng": -87.6890,
        "emoji": "🍢",
        "bannerGradient": "linear-gradient(135deg, #4A0E0E 0%, #8B1A1A 100%)",
    },
    {
        "id": 5,
        "name": "Kabul House",
        "cuisine": ["Afghan"],
        "area": "Northbrook",
        "address": "3320 Dundee Rd, Northbrook, IL 60062",
        "phone": "(847) 559-0600",
        "rating": 4.8,
        "reviewCount": 734,
        "priceRange": "$$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2010,
        "description": "Widely considered the best Afghan restaurant in the Chicago metro area, Kabul House delivers an exceptional dining experience with dishes like lamb shank, mantu dumplings, and aushak. The warm, elegant atmosphere and extraordinary service have earned it a devoted following across all faiths.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "Closed", "Tue": "11:30 AM – 9:30 PM", "Wed": "11:30 AM – 9:30 PM",
            "Thu": "11:30 AM – 9:30 PM", "Fri": "11:30 AM – 10 PM", "Sat": "11:30 AM – 10 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Kabul+House+Northbrook+IL",
        "lat": 42.1275, "lng": -87.8285,
        "emoji": "🫕",
        "bannerGradient": "linear-gradient(135deg, #2D1B69 0%, #5B3FC3 100%)",
    },
    {
        "id": 6,
        "name": "Shawarma Palace",
        "cuisine": ["Middle Eastern", "Lebanese"],
        "area": "Schaumburg",
        "address": "1136 E Higgins Rd, Schaumburg, IL 60173",
        "phone": "(847) 524-1000",
        "rating": 4.3,
        "reviewCount": 488,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2014,
        "description": "A go-to spot for northwest suburban halal seekers, Shawarma Palace serves generous portions of freshly carved chicken and beef shawarma, crispy falafel, and creamy hummus. Quick service and a comfortable setting make it perfect for families and lunch crowds alike.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Shawarma+Palace+Schaumburg+IL",
        "lat": 42.0334, "lng": -88.0512,
        "emoji": "🥗",
        "bannerGradient": "linear-gradient(135deg, #1A3A5C 0%, #1B6CA8 100%)",
    },
    {
        "id": 7,
        "name": "Sultan's Market",
        "cuisine": ["Middle Eastern", "Mediterranean"],
        "area": "Chicago (Wicker Park)",
        "address": "2057 W North Ave, Chicago, IL 60647",
        "phone": "(773) 235-3474",
        "rating": 4.4,
        "reviewCount": 921,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2009,
        "description": "A Chicago institution in Wicker Park, Sultan's Market is beloved for its fresh, affordable Middle Eastern fare. Their chicken shawarma wraps, falafel sandwiches, and spinach pies are local favorites. The compact diner-style setup keeps prices low without sacrificing quality.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "10 AM – 10 PM", "Tue": "10 AM – 10 PM", "Wed": "10 AM – 10 PM",
            "Thu": "10 AM – 10 PM", "Fri": "10 AM – 11 PM", "Sat": "10 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Sultan's+Market+Chicago+IL",
        "lat": 41.9100, "lng": -87.6780,
        "emoji": "🧆",
        "bannerGradient": "linear-gradient(135deg, #14532D 0%, #166534 100%)",
    },
    {
        "id": 8,
        "name": "Golden Kabob",
        "cuisine": ["Persian", "Middle Eastern"],
        "area": "Skokie",
        "address": "9356 N Milwaukee Ave, Niles, IL 60714",
        "phone": "(847) 588-0550",
        "rating": 4.5,
        "reviewCount": 567,
        "priceRange": "$$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2012,
        "description": "Golden Kabob brings the rich flavors of Persian cuisine to the north suburbs. Their saffron-marinated chicken, tender koobideh, and fragrant basmati rice are prepared with traditional recipes passed down through generations. A refined dining experience in an inviting setting.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 9:30 PM", "Tue": "11 AM – 9:30 PM", "Wed": "11 AM – 9:30 PM",
            "Thu": "11 AM – 9:30 PM", "Fri": "11 AM – 10:30 PM", "Sat": "11 AM – 10:30 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Golden+Kabob+Niles+IL",
        "lat": 42.0189, "lng": -87.8267,
        "emoji": "🍖",
        "bannerGradient": "linear-gradient(135deg, #78350F 0%, #D97706 100%)",
    },
    {
        "id": 9,
        "name": "Hira's Restaurant & Catering",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Devon Ave)",
        "address": "2731 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 764-5353",
        "rating": 4.3,
        "reviewCount": 398,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2011,
        "description": "Hira's is a Devon Avenue staple known for hearty Pakistani home cooking. Their haleem, paya, and nihari are slow-cooked to perfection, and the lunch buffet is one of the best deals on the street. Also offers full catering services for weddings and events.",
        "features": ["Dine-in", "Takeout", "Catering", "Buffet"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Hira's+Restaurant+Chicago+IL",
        "lat": 41.9979, "lng": -87.6900,
        "emoji": "🍲",
        "bannerGradient": "linear-gradient(135deg, #7B2D00 0%, #9A3412 100%)",
    },
    {
        "id": 10,
        "name": "Al Tarboush",
        "cuisine": ["Lebanese", "Mediterranean"],
        "area": "Chicago (Near North)",
        "address": "1060 N Dearborn St, Chicago, IL 60610",
        "phone": "(312) 751-5005",
        "rating": 4.2,
        "reviewCount": 445,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2015,
        "description": "Al Tarboush brings authentic Lebanese hospitality to Chicago's Near North side. Their mezze spreads, fattoush, and kafta platters offer a genuine taste of Beirut. An excellent option for downtown diners looking for certified Zabiha Halal Lebanese food.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Al+Tarboush+Chicago+IL",
        "lat": 41.9030, "lng": -87.6298,
        "emoji": "🫒",
        "bannerGradient": "linear-gradient(135deg, #064E3B 0%, #059669 100%)",
    },
    {
        "id": 11,
        "name": "Holy Land Grocery & Deli",
        "cuisine": ["Mediterranean", "Middle Eastern"],
        "area": "Chicago (Albany Park)",
        "address": "4806 N Kedzie Ave, Chicago, IL 60625",
        "phone": "(773) 588-3306",
        "rating": 4.6,
        "reviewCount": 712,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2001,
        "description": "Both a grocery store and an acclaimed deli, Holy Land is a neighborhood gem in Albany Park. Pick up certified halal meats from the butcher counter or grab a ready-made plate of stuffed grape leaves, baba ganoush, and kibbeh. A true community anchor since the 1980s.",
        "features": ["Dine-in", "Takeout", "Grocery"],
        "hours": {
            "Mon": "8 AM – 9 PM", "Tue": "8 AM – 9 PM", "Wed": "8 AM – 9 PM",
            "Thu": "8 AM – 9 PM", "Fri": "8 AM – 10 PM", "Sat": "8 AM – 10 PM", "Sun": "9 AM – 8 PM",
        },
        "mapsQuery": "Holy+Land+Grocery+Chicago+IL",
        "lat": 41.9685, "lng": -87.7078,
        "emoji": "🫙",
        "bannerGradient": "linear-gradient(135deg, #1E3A5F 0%, #2563EB 100%)",
    },
    {
        "id": 12,
        "name": "Afghan Kabob House",
        "cuisine": ["Afghan"],
        "area": "Niles",
        "address": "8140 N Milwaukee Ave, Niles, IL 60714",
        "phone": "(847) 966-9600",
        "rating": 4.4,
        "reviewCount": 329,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2013,
        "description": "A hidden gem in Niles, Afghan Kabob House serves traditional Afghan dishes with warmth and authenticity. Their chapli kabob, qabuli pulao rice, and bolani flatbreads are crowd favorites. Affordable prices and generous portions make it a must-visit for Afghan food enthusiasts.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 9 PM", "Tue": "11 AM – 9 PM", "Wed": "11 AM – 9 PM",
            "Thu": "11 AM – 9 PM", "Fri": "11 AM – 10 PM", "Sat": "11 AM – 10 PM", "Sun": "12 PM – 8 PM",
        },
        "mapsQuery": "Afghan+Kabob+House+Niles+IL",
        "lat": 42.0080, "lng": -87.8130,
        "emoji": "🫕",
        "bannerGradient": "linear-gradient(135deg, #312E81 0%, #4F46E5 100%)",
    },
    {
        "id": 13,
        "name": "Mediterranean Grill",
        "cuisine": ["Turkish", "Mediterranean"],
        "area": "Oak Lawn",
        "address": "5347 W 95th St, Oak Lawn, IL 60453",
        "phone": "(708) 636-4525",
        "rating": 4.3,
        "reviewCount": 276,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2016,
        "description": "Mediterranean Grill brings the flavors of Turkish cuisine to the southwest suburbs. Their Adana kebab, pide flatbread pizzas, and hearty lentil soup reflect the depth and diversity of Turkish-Mediterranean cooking. Cozy atmosphere with excellent weekend specials.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 9:30 PM", "Tue": "11 AM – 9:30 PM", "Wed": "11 AM – 9:30 PM",
            "Thu": "11 AM – 9:30 PM", "Fri": "11 AM – 10:30 PM", "Sat": "11 AM – 10:30 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Mediterranean+Grill+Oak+Lawn+IL",
        "lat": 41.7212, "lng": -87.7565,
        "emoji": "🥘",
        "bannerGradient": "linear-gradient(135deg, #7F1D1D 0%, #B91C1C 100%)",
    },
    {
        "id": 14,
        "name": "Salam Restaurant",
        "cuisine": ["Lebanese", "Mediterranean"],
        "area": "Oak Lawn",
        "address": "4901 W 95th St, Oak Lawn, IL 60453",
        "phone": "(708) 422-4444",
        "rating": 4.5,
        "reviewCount": 524,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2007,
        "description": "Salam Restaurant is a beloved fixture in Oak Lawn's Arab-American community. Their rotisserie chicken, garlic sauce (toum), and freshly baked bread have kept regulars returning for years. An unpretentious spot with authentic flavors and welcoming service.",
        "features": ["Dine-in", "Takeout", "Delivery", "Catering"],
        "hours": {
            "Mon": "10 AM – 11 PM", "Tue": "10 AM – 11 PM", "Wed": "10 AM – 11 PM",
            "Thu": "10 AM – 11 PM", "Fri": "10 AM – 12 AM", "Sat": "10 AM – 12 AM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Salam+Restaurant+Oak+Lawn+IL",
        "lat": 41.7212, "lng": -87.7480,
        "emoji": "🍗",
        "bannerGradient": "linear-gradient(135deg, #134E4A 0%, #0F766E 100%)",
    },
    {
        "id": 15,
        "name": "Zam Zam Restaurant",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Devon Ave)",
        "address": "2408 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 764-9494",
        "rating": 4.2,
        "reviewCount": 347,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2009,
        "description": "Named after the sacred well in Mecca, Zam Zam has served the Devon Ave community with hearty Pakistani food for over 20 years. Their saag, daal makhani, and naan fresh from the tandoor oven are standout dishes. An approachable, no-frills spot with genuine flavor.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Zam+Zam+Restaurant+Chicago+IL",
        "lat": 41.9979, "lng": -87.6860,
        "emoji": "🍛",
        "bannerGradient": "linear-gradient(135deg, #78350F 0%, #B45309 100%)",
    },
    {
        "id": 16,
        "name": "Anmol Restaurant",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Devon Ave)",
        "address": "2726 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 764-1110",
        "rating": 4.4,
        "reviewCount": 419,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2010,
        "description": "Anmol (meaning 'priceless' in Urdu) lives up to its name with exceptional Pakistani and North Indian cuisine at unbeatable prices. Their mixed grill platter, lamb chops, and seekh kebabs are highlights. A vibrant atmosphere with live music on select weekends.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "12 PM – 11 PM", "Tue": "12 PM – 11 PM", "Wed": "12 PM – 11 PM",
            "Thu": "12 PM – 11 PM", "Fri": "12 PM – 12 AM", "Sat": "12 PM – 12 AM", "Sun": "12 PM – 11 PM",
        },
        "mapsQuery": "Anmol+Restaurant+Chicago+IL",
        "lat": 41.9979, "lng": -87.6895,
        "emoji": "🍢",
        "bannerGradient": "linear-gradient(135deg, #4A1942 0%, #831843 100%)",
    },
    {
        "id": 17,
        "name": "Punjab Tandoor",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Devon Ave)",
        "address": "2358 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 338-2080",
        "rating": 4.1,
        "reviewCount": 288,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2008,
        "description": "Punjab Tandoor specializes in clay oven cooking, producing beautifully charred naan, tandoori chicken, and lamb chops with a smoky depth you can't get any other way. Their daily lunch specials offer incredible value for authentic Punjabi dishes.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Punjab+Tandoor+Chicago+IL",
        "lat": 41.9979, "lng": -87.6850,
        "emoji": "🫓",
        "bannerGradient": "linear-gradient(135deg, #7C2D12 0%, #EA580C 100%)",
    },
    {
        "id": 18,
        "name": "Naf Naf Grill",
        "cuisine": ["Middle Eastern", "Mediterranean"],
        "area": "Chicago (Loop)",
        "address": "233 S Wacker Dr, Chicago, IL 60606",
        "phone": "(312) 466-9999",
        "rating": 4.2,
        "reviewCount": 673,
        "priceRange": "$",
        "certifiedBy": "Islamic Food & Nutrition Council of America (IFANCA)",
        "certYear": 2011,
        "description": "A popular fast-casual Middle Eastern chain with deep Chicago roots, Naf Naf Grill is known for its pillowy pita bread baked fresh on-site, hearty shawarma bowls, and vibrant toppings bar. Multiple Chicago-area locations make it one of the most accessible Zabiha Halal options in the city.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "10:30 AM – 9 PM", "Tue": "10:30 AM – 9 PM", "Wed": "10:30 AM – 9 PM",
            "Thu": "10:30 AM – 9 PM", "Fri": "10:30 AM – 9 PM", "Sat": "11 AM – 8 PM", "Sun": "11 AM – 7 PM",
        },
        "mapsQuery": "Naf+Naf+Grill+Chicago+Loop+IL",
        "lat": 41.8788, "lng": -87.6360,
        "emoji": "🌯",
        "bannerGradient": "linear-gradient(135deg, #1C4532 0%, #276749 100%)",
    },
    {
        "id": 19,
        "name": "Taste of Lebanon",
        "cuisine": ["Lebanese", "Mediterranean"],
        "area": "Chicago (Rogers Park)",
        "address": "6649 N Clark St, Chicago, IL 60626",
        "phone": "(773) 262-1450",
        "rating": 4.5,
        "reviewCount": 382,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2012,
        "description": "Tucked into Rogers Park, Taste of Lebanon is a neighborhood gem beloved for its fresh, affordable Lebanese food. Their chicken tawook wraps, fresh fattoush salad, and house-made baklava for dessert keep the locals coming back. Cozy dining room with a family-run warmth.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Taste+of+Lebanon+Chicago+IL",
        "lat": 42.0018, "lng": -87.6738,
        "emoji": "🥙",
        "bannerGradient": "linear-gradient(135deg, #14532D 0%, #15803D 100%)",
    },
    {
        "id": 20,
        "name": "Al Khayam",
        "cuisine": ["Pakistani", "Afghan"],
        "area": "Chicago (Devon Ave)",
        "address": "2527 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 465-5990",
        "rating": 4.0,
        "reviewCount": 214,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Committee",
        "certYear": 2014,
        "description": "Al Khayam blends Pakistani and Afghan culinary traditions to create a unique menu that features the best of both cuisines. Their mutton karahi, Afghan qabuli rice, and home-style stews reflect a genuine cross-cultural heritage. Warm hospitality in a comfortable setting.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "12 PM – 10 PM", "Tue": "12 PM – 10 PM", "Wed": "12 PM – 10 PM",
            "Thu": "12 PM – 10 PM", "Fri": "12 PM – 11 PM", "Sat": "12 PM – 11 PM", "Sun": "1 PM – 9 PM",
        },
        "mapsQuery": "Al+Khayam+Chicago+IL",
        "lat": 41.9979, "lng": -87.6880,
        "emoji": "🍲",
        "bannerGradient": "linear-gradient(135deg, #1E1B4B 0%, #3730A3 100%)",
    },
    # ── The 20 entries below (ids 21-40) were compiled from public, verifiable
    # sources: name/address/cuisine cross-checked against Zabihah restaurant
    # listings, phone numbers found via independent web search, and halal
    # certification confirmed directly against Halal Monitoring Services'
    # (hmsusa.org) own certified-restaurant detail pages. HMS does not publish
    # an original certification year per restaurant (only rolling audit/renewal
    # dates), so certYear is left as None rather than guessed — the modal UI
    # omits the "(since YYYY)" clause when certYear is falsy.
    {
        "id": 21,
        "name": "Hyderabad House",
        "cuisine": ["Indian", "Pakistani"],
        "area": "Chicago (Devon Ave)",
        "address": "2225 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 338-5566",
        "rating": 4.5,
        "reviewCount": 165,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Devon Avenue favorite specializing in Hyderabadi cuisine, Hyderabad House is known for its slow-cooked biryani, haleem, and irani chai. HMS-certified and a regular stop for anyone touring Chicago's South Asian halal food scene.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Hyderabad+House+Devon+Ave+Chicago+IL",
        "lat": 41.9986, "lng": -87.6960,
        "emoji": "🍛",
        "bannerGradient": "linear-gradient(135deg, #6B21A8 0%, #9333EA 100%)",
    },
    {
        "id": 22,
        "name": "Hadramout Restaurant & Bakery",
        "cuisine": ["Yemeni"],
        "area": "Chicago (Devon Ave)",
        "address": "3100 W Devon Ave, Chicago, IL 60659",
        "phone": "(773) 942-7541",
        "rating": 4.4,
        "reviewCount": 267,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "Part restaurant, part bakery, Hadramout brings Yemeni classics like mandi and fahsa to Devon Avenue alongside fresh-baked bread straight from the in-house oven. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Bakery"],
        "hours": {
            "Mon": "9 AM – 11 PM", "Tue": "9 AM – 11 PM", "Wed": "9 AM – 11 PM",
            "Thu": "9 AM – 11 PM", "Fri": "9 AM – 12 AM", "Sat": "9 AM – 12 AM", "Sun": "9 AM – 11 PM",
        },
        "mapsQuery": "Hadramout+Restaurant+Bakery+Devon+Ave+Chicago+IL",
        "lat": 41.9979, "lng": -87.7130,
        "emoji": "🍯",
        "bannerGradient": "linear-gradient(135deg, #92400E 0%, #D97706 100%)",
    },
    {
        "id": 23,
        "name": "Al Kabeer Restaurant",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (West Rogers Park)",
        "address": "6426 N Western Ave, Chicago, IL 60645",
        "phone": "(224) 724-9111",
        "rating": 4.0,
        "reviewCount": 12,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A late-night West Rogers Park spot known for charcoal-grilled seekh kebabs and boti, popular with the neighborhood's South Asian community. HMS-certified.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "4 PM – 2 AM", "Tue": "4 PM – 2 AM", "Wed": "3 PM – 2 AM",
            "Thu": "4 PM – 2 AM", "Fri": "4 PM – 2 AM", "Sat": "4 PM – 2 AM", "Sun": "4 PM – 2 AM",
        },
        "mapsQuery": "Al+Kabeer+Restaurant+Western+Ave+Chicago+IL",
        "lat": 41.9986, "lng": -87.6900,
        "emoji": "🍢",
        "bannerGradient": "linear-gradient(135deg, #7C2D12 0%, #C2410C 100%)",
    },
    {
        "id": 24,
        "name": "Al Safa Restaurant",
        "cuisine": ["Pakistani", "Middle Eastern"],
        "area": "Chicago (West Rogers Park)",
        "address": "3146 W Touhy Ave, Chicago, IL 60645",
        "phone": "(773) 654-1664",
        "rating": 4.2,
        "reviewCount": 88,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A no-frills West Rogers Park counter serving fresh halal meat cuts alongside grilled plates, popular for quick lunches and family orders alike. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Grocery"],
        "hours": {
            "Mon": "10 AM – 9 PM", "Tue": "10 AM – 9 PM", "Wed": "10 AM – 9 PM",
            "Thu": "10 AM – 9 PM", "Fri": "10 AM – 9 PM", "Sat": "10 AM – 9 PM", "Sun": "10 AM – 8 PM",
        },
        "mapsQuery": "Al+Safa+Restaurant+Touhy+Ave+Chicago+IL",
        "lat": 42.0122, "lng": -87.7135,
        "emoji": "🥩",
        "bannerGradient": "linear-gradient(135deg, #7F1D1D 0%, #DC2626 100%)",
    },
    {
        "id": 25,
        "name": "Tabaq Restaurant",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Chicago (Near North)",
        "address": "1245 N Clybourn Ave, Chicago, IL 60610",
        "phone": "(312) 944-1245",
        "rating": 4.3,
        "reviewCount": 210,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Near North fixture for over two decades, Tabaq serves grilled kebabs, karahi, and biryani late into the night. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "10 AM – 1 AM", "Tue": "10 AM – 1 AM", "Wed": "10 AM – 1 AM",
            "Thu": "10 AM – 1 AM", "Fri": "10 AM – 3 AM", "Sat": "10 AM – 3 AM", "Sun": "10 AM – 1 AM",
        },
        "mapsQuery": "Tabaq+Restaurant+Clybourn+Ave+Chicago+IL",
        "lat": 41.9075, "lng": -87.6520,
        "emoji": "🍖",
        "bannerGradient": "linear-gradient(135deg, #78350F 0%, #B45309 100%)",
    },
    {
        "id": 26,
        "name": "Al Halal Zaiqa",
        "cuisine": ["Pakistani", "Desi"],
        "area": "Chicago (Near North)",
        "address": "449 W North Ave, Chicago, IL 60610",
        "phone": "(312) 763-6972",
        "rating": 4.1,
        "reviewCount": 145,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A North Avenue late-night destination for Desi comfort food — nihari, karahi, and fresh naan served well past midnight on weekends. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "2 PM – 12 AM", "Tue": "11 AM – 3 AM", "Wed": "11 AM – 3 AM",
            "Thu": "11 AM – 3 AM", "Fri": "11 AM – 3 AM", "Sat": "11 AM – 3:30 AM", "Sun": "11 AM – 3 AM",
        },
        "mapsQuery": "Al+Halal+Zaiqa+North+Ave+Chicago+IL",
        "lat": 41.9108, "lng": -87.6382,
        "emoji": "🍲",
        "bannerGradient": "linear-gradient(135deg, #713F12 0%, #A16207 100%)",
    },
    {
        "id": 27,
        "name": "Sheikhs N Burgers",
        "cuisine": ["American"],
        "area": "Skokie",
        "address": "7158 Carpenter Rd, Skokie, IL 60077",
        "phone": "(224) 470-6266",
        "rating": 4.5,
        "reviewCount": 10,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "An all-halal American burger joint in Skokie, serving smash burgers, crinkle fries, and shakes for a crowd that grew up without halal fast food. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Sheikhs+N+Burgers+Skokie+IL",
        "lat": 42.0247, "lng": -87.7515,
        "emoji": "🍔",
        "bannerGradient": "linear-gradient(135deg, #7C2D12 0%, #EA580C 100%)",
    },
    {
        "id": 28,
        "name": "Halal Pizza Point",
        "cuisine": ["Pizza", "American"],
        "area": "Skokie",
        "address": "5230 Dempster St, Skokie, IL 60077",
        "phone": "(224) 534-7353",
        "rating": 4.3,
        "reviewCount": 95,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "Skokie's all-halal pizzeria, topping fresh dough with halal pepperoni and sausage for families who'd otherwise have to skip pizza night. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "11:30 AM – 10 PM", "Tue": "11:30 AM – 10 PM", "Wed": "11:30 AM – 10 PM",
            "Thu": "11:30 AM – 10 PM", "Fri": "11:30 AM – 10 PM", "Sat": "11:30 AM – 10 PM", "Sun": "11:30 AM – 10 PM",
        },
        "mapsQuery": "Halal+Pizza+Point+Dempster+St+Skokie+IL",
        "lat": 42.0387, "lng": -87.7460,
        "emoji": "🍕",
        "bannerGradient": "linear-gradient(135deg, #7F1D1D 0%, #B91C1C 100%)",
    },
    {
        "id": 29,
        "name": "Hello Shawarma",
        "cuisine": ["Middle Eastern"],
        "area": "Niles",
        "address": "5606 Touhy Ave, Niles, IL 60714",
        "phone": "(847) 636-4444",
        "rating": 4.4,
        "reviewCount": 130,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "Part of a small local chain, this Niles location layers shaved chicken and beef shawarma into wraps and platters with a well-loved garlic sauce. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "10 AM – 12 AM", "Tue": "10 AM – 12 AM", "Wed": "10 AM – 12 AM",
            "Thu": "10 AM – 12 AM", "Fri": "10 AM – 1 AM", "Sat": "10 AM – 12 AM", "Sun": "10 AM – 12 AM",
        },
        "mapsQuery": "Hello+Shawarma+Touhy+Ave+Niles+IL",
        "lat": 42.0122, "lng": -87.8090,
        "emoji": "🌯",
        "bannerGradient": "linear-gradient(135deg, #14532D 0%, #16A34A 100%)",
    },
    {
        "id": 30,
        "name": "Afghan Kabob",
        "cuisine": ["Afghan"],
        "area": "Morton Grove",
        "address": "6002 W Dempster St, Morton Grove, IL 60053",
        "phone": "(224) 534-7262",
        "rating": 4.5,
        "reviewCount": 210,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Morton Grove spot for charbroiled kabobs, qabuli pulao, and mantu, drawing regulars from across the North Shore for its smoky grill flavor. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 9 PM", "Tue": "11 AM – 9 PM", "Wed": "11 AM – 9 PM",
            "Thu": "11 AM – 9 PM", "Fri": "11 AM – 10 PM", "Sat": "11 AM – 10 PM", "Sun": "12 PM – 8 PM",
        },
        "mapsQuery": "Afghan+Kabob+Dempster+St+Morton+Grove+IL",
        "lat": 42.0398, "lng": -87.7830,
        "emoji": "🍢",
        "bannerGradient": "linear-gradient(135deg, #312E81 0%, #4338CA 100%)",
    },
    {
        "id": 31,
        "name": "Maria's Halal Pizzeria",
        "cuisine": ["Pizza", "American"],
        "area": "Des Plaines",
        "address": "590 Potter Rd, Des Plaines, IL 60016",
        "phone": "(847) 297-7181",
        "rating": 4.4,
        "reviewCount": 175,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A neighborhood pizzeria in Des Plaines serving halal chicken and beef topped pies alongside classic Chicago-style thin crust. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Delivery"],
        "hours": {
            "Mon": "12 PM – 9 PM", "Tue": "12 PM – 9 PM", "Wed": "12 PM – 9 PM",
            "Thu": "12 PM – 9 PM", "Fri": "12 PM – 10 PM", "Sat": "12 PM – 10 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Maria's+Halal+Pizzeria+Potter+Rd+Des+Plaines+IL",
        "lat": 42.0453, "lng": -87.8720,
        "emoji": "🍕",
        "bannerGradient": "linear-gradient(135deg, #9A3412 0%, #EA580C 100%)",
    },
    {
        "id": 32,
        "name": "Kolachi Tandoori Grill Express",
        "cuisine": ["Pakistani", "Indian"],
        "area": "Schaumburg",
        "address": "937 S Roselle Rd, Schaumburg, IL 60193",
        "phone": "(630) 339-9002",
        "rating": 4.5,
        "reviewCount": 50,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Roselle Road strip-mall favorite for tandoori chicken, seekh kebabs, and daily lunch specials at a fast-casual pace. HMS-certified.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 9:30 PM", "Tue": "11 AM – 9:30 PM", "Wed": "11 AM – 9:30 PM",
            "Thu": "11 AM – 9:30 PM", "Fri": "11 AM – 10 PM", "Sat": "11 AM – 10 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Kolachi+Tandoori+Grill+Express+Roselle+Rd+Schaumburg+IL",
        "lat": 42.0184, "lng": -88.0847,
        "emoji": "🍗",
        "bannerGradient": "linear-gradient(135deg, #7C2D12 0%, #D97706 100%)",
    },
    {
        "id": 33,
        "name": "Ali Baba Kabab",
        "cuisine": ["Mediterranean", "Persian"],
        "area": "Schaumburg",
        "address": "869 S Roselle Rd, Schaumburg, IL 60193",
        "phone": "(630) 912-4499",
        "rating": 4.6,
        "reviewCount": 131,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A longtime Schaumburg favorite for Persian-style koobideh and chicken kabob plates, with generous rice portions and a loyal following. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 9:30 PM", "Tue": "11 AM – 9:30 PM", "Wed": "11 AM – 9:30 PM",
            "Thu": "11 AM – 9:30 PM", "Fri": "11 AM – 10 PM", "Sat": "11 AM – 10 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Ali+Baba+Kabab+Roselle+Rd+Schaumburg+IL",
        "lat": 42.0195, "lng": -88.0845,
        "emoji": "🥙",
        "bannerGradient": "linear-gradient(135deg, #164E63 0%, #0E7490 100%)",
    },
    {
        "id": 34,
        "name": "Sweet Reserve Cafe & Bakery",
        "cuisine": ["Bakery", "Desserts"],
        "area": "Schaumburg",
        "address": "160 S Roselle Rd C, Schaumburg, IL 60193",
        "phone": "(630) 376-6150",
        "rating": 4.7,
        "reviewCount": 59,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A halal-certified cafe and bakery turning out custom cakes, pastries, and coffee drinks — a rare all-halal dessert stop in the northwest suburbs. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Bakery"],
        "hours": {
            "Mon": "8 AM – 10 PM", "Tue": "8 AM – 10 PM", "Wed": "8 AM – 10 PM",
            "Thu": "8 AM – 10 PM", "Fri": "8 AM – 10 PM", "Sat": "8 AM – 10 PM", "Sun": "8 AM – 10 PM",
        },
        "mapsQuery": "Sweet+Reserve+Cafe+Bakery+Roselle+Rd+Schaumburg+IL",
        "lat": 42.0298, "lng": -88.0840,
        "emoji": "🧁",
        "bannerGradient": "linear-gradient(135deg, #831843 0%, #DB2777 100%)",
    },
    {
        "id": 35,
        "name": "Kabul Kabob",
        "cuisine": ["Afghan"],
        "area": "Bridgeview",
        "address": "7265 W 87th St, Bridgeview, IL 60455",
        "phone": "(708) 529-0590",
        "rating": 4.8,
        "reviewCount": 127,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Bridgeview standout for Afghan charbroiled kabobs and fluffy basmati rice, drawing some of the highest ratings of any restaurant on this list. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Kabul+Kabob+87th+St+Bridgeview+IL",
        "lat": 41.7376, "lng": -87.8095,
        "emoji": "🍖",
        "bannerGradient": "linear-gradient(135deg, #1E1B4B 0%, #4338CA 100%)",
    },
    {
        "id": 36,
        "name": "BBQLAND Restaurant",
        "cuisine": ["BBQ", "Middle Eastern"],
        "area": "Hanover Park",
        "address": "1234 E Lake St, Hanover Park, IL 60133",
        "phone": "(630) 855-6274",
        "rating": 4.2,
        "reviewCount": 60,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A Hanover Park grill house specializing in charcoal-cooked chicken, lamb, and goat platters for the western suburbs' halal BBQ crowd. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 9:30 PM", "Tue": "11 AM – 9:30 PM", "Wed": "11 AM – 9:30 PM",
            "Thu": "11 AM – 9:30 PM", "Fri": "11 AM – 10:30 PM", "Sat": "11 AM – 10:30 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "BBQLAND+Restaurant+Lake+St+Hanover+Park+IL",
        "lat": 41.9990, "lng": -88.1420,
        "emoji": "🍖",
        "bannerGradient": "linear-gradient(135deg, #451A03 0%, #92400E 100%)",
    },
    {
        "id": 37,
        "name": "The Halal Steakhouse",
        "cuisine": ["Steakhouse", "American"],
        "area": "Hanover Park",
        "address": "2020 Army Trail Rd, Hanover Park, IL 60133",
        "phone": "(315) 975-2600",
        "rating": 4.1,
        "reviewCount": 40,
        "priceRange": "$$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "An all-halal steakhouse concept in Hanover Park, bringing certified halal beef cuts to a sit-down steakhouse format rare in the Chicago suburbs. HMS-certified.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "5 PM – 11 PM", "Tue": "5 PM – 11 PM", "Wed": "Closed",
            "Thu": "12 PM – 11 PM", "Fri": "12 PM – 11 PM", "Sat": "12 PM – 11 PM", "Sun": "12 PM – 11 PM",
        },
        "mapsQuery": "The+Halal+Steakhouse+Army+Trail+Rd+Hanover+Park+IL",
        "lat": 41.9975, "lng": -88.1520,
        "emoji": "🥩",
        "bannerGradient": "linear-gradient(135deg, #450A0A 0%, #991B1B 100%)",
    },
    {
        "id": 38,
        "name": "Milliy Family Restaurant",
        "cuisine": ["Uzbek", "Central Asian"],
        "area": "Naperville",
        "address": "1279 Rickert Dr, Naperville, IL 60540",
        "phone": "(630) 995-3695",
        "rating": 4.4,
        "reviewCount": 70,
        "priceRange": "$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A rare Uzbek option in the western suburbs, Milliy Family serves plov, shashlik, and fresh-baked non bread in a warm, family-run dining room. HMS-certified.",
        "features": ["Dine-in", "Takeout"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "Closed",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 10 PM", "Sat": "11 AM – 10 PM", "Sun": "11 AM – 10 PM",
        },
        "mapsQuery": "Milliy+Family+Restaurant+Rickert+Dr+Naperville+IL",
        "lat": 41.7530, "lng": -88.1620,
        "emoji": "🍲",
        "bannerGradient": "linear-gradient(135deg, #164E63 0%, #0891B2 100%)",
    },
    {
        "id": 39,
        "name": "Reza's Restaurant",
        "cuisine": ["Persian", "Mediterranean"],
        "area": "Oak Brook",
        "address": "40 N Tower Rd, Oak Brook, IL 60523",
        "phone": "(630) 424-9900",
        "rating": 4.3,
        "reviewCount": 450,
        "priceRange": "$$$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "A long-running Chicagoland Persian dining institution, Reza's Oak Brook location serves saffron-marinated kabobs and a full mezze spread in an upscale setting. HMS-certified.",
        "features": ["Dine-in", "Takeout", "Catering"],
        "hours": {
            "Mon": "11 AM – 10 PM", "Tue": "11 AM – 10 PM", "Wed": "11 AM – 10 PM",
            "Thu": "11 AM – 10 PM", "Fri": "11 AM – 11 PM", "Sat": "11 AM – 11 PM", "Sun": "12 PM – 9 PM",
        },
        "mapsQuery": "Reza's+Restaurant+Tower+Rd+Oak+Brook+IL",
        "lat": 41.8420, "lng": -87.9550,
        "emoji": "🍢",
        "bannerGradient": "linear-gradient(135deg, #3F6212 0%, #65A30D 100%)",
    },
    {
        "id": 40,
        "name": "Mediterranean Market",
        "cuisine": ["Mediterranean", "Middle Eastern"],
        "area": "Lombard",
        "address": "612 E Roosevelt Rd, Lombard, IL 60148",
        "phone": "(630) 424-1397",
        "rating": 4.5,
        "reviewCount": 45,
        "priceRange": "$",
        "certifiedBy": "Halal Monitoring Services (HMS)",
        "certYear": None,
        "description": "Part grocery, part deli counter, Mediterranean Market sells fresh halal cuts alongside ready-made hummus, falafel, and stuffed grape leaves for the western suburbs. HMS-certified.",
        "features": ["Takeout", "Grocery"],
        "hours": {
            "Mon": "8 AM – 10 PM", "Tue": "8 AM – 10 PM", "Wed": "8 AM – 10 PM",
            "Thu": "8 AM – 10 PM", "Fri": "8 AM – 10 PM", "Sat": "8 AM – 10 PM", "Sun": "8 AM – 10 PM",
        },
        "mapsQuery": "Mediterranean+Market+Roosevelt+Rd+Lombard+IL",
        "lat": 41.8600, "lng": -88.0020,
        "emoji": "🫙",
        "bannerGradient": "linear-gradient(135deg, #1E3A5F 0%, #2563EB 100%)",
    },
]


def get_or_create(cache, model, name):
    if name not in cache:
        instance = model.query.filter_by(name=name).first()
        if instance is None:
            instance = model(name=name)
            db.session.add(instance)
        cache[name] = instance
    return cache[name]


def seed():
    app = create_app()
    with app.app_context():
        db.drop_all()
        db.create_all()

        cuisine_cache = {}
        feature_cache = {}

        for data in RESTAURANTS_DATA:
            restaurant = Restaurant(
                id=data["id"],
                name=data["name"],
                area=data["area"],
                address=data["address"],
                phone=data["phone"],
                rating=data["rating"],
                review_count=data["reviewCount"],
                price_range=data["priceRange"],
                certified_by=data["certifiedBy"],
                cert_year=data["certYear"],
                description=data["description"],
                maps_query=data["mapsQuery"],
                lat=data["lat"],
                lng=data["lng"],
                emoji=data["emoji"],
                banner_gradient=data["bannerGradient"],
            )
            restaurant.cuisines = [get_or_create(cuisine_cache, Cuisine, c) for c in data["cuisine"]]
            restaurant.features = [get_or_create(feature_cache, Feature, f) for f in data["features"]]
            restaurant.hours = [
                Hour(day=day, day_order=order, time_range=data["hours"][day])
                for order, day in enumerate(DAYS)
            ]
            db.session.add(restaurant)

        db.session.commit()

        if db.engine.dialect.name == "postgresql":
            # Explicit ids were assigned above, so the identity sequence
            # doesn't know about them yet — resync it or the next
            # auto-generated insert will collide with an existing id.
            db.session.execute(text(
                "SELECT setval(pg_get_serial_sequence('restaurants', 'id'), "
                "COALESCE((SELECT MAX(id) FROM restaurants), 1))"
            ))
            db.session.commit()

        print(f"Seeded {len(RESTAURANTS_DATA)} restaurants.")


if __name__ == "__main__":
    seed()
